# This is a basic workflow to help you get started with Actions

name: Build_Vim_Deb_Package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies
        run: | 
          # liblua5.1-dev for ubuntu
          sudo apt install -y git libncurses5-dev libncurses5 \
            libgtk2.0-dev libatk1.0-dev libcairo2-dev libx11-dev libxpm-dev \
            libxt-dev python-dev python3-dev ruby-dev lua5.1 liblua5.1-dev checkinstall
            
      - name: Clone repository
        run: git clone https://github.com/vim/vim

      - name: Compile source code
        run: |
          cd vim
          ./configure --with-features=huge \
              --enable-multibyte \
              --enable-rubyinterp \
              --enable-pythoninterp \
              --enable-perlinterp \
              --enable-luainterp \
              --enable-gui=false \
              --enable-cscope 
          make -j8
            
      - name: Pack to .deb
        run: |
          cd vim
          sudo checkinstall --default -D vim82.deb
          
      - name: Test package
        run: |
          # remove old vim package
          cd vim
          sudo apt remove -y vim vim-runtime gvim
          sudo apt remove -y vim-tiny vim-common vim-gui-common vim-nox
          sudo rm -rf /usr/share/vim
          # install
          sudo dpkg -i --force-overwrite vim*.deb
          vim --version
          pwd
          ls
          cp *.deb ../vim82.deb

      - name: Store generated APK file
        uses: actions/upload-artifact@v1
        with:
          name: vim82
          path: ./vim82.deb
        #     - name: Upload Apk to WeTransfer
        #       run: |
        #         cd termux-app
        #          curl -sL https://git.io/file-transfer | sh
        #         ./transfer wet ./app/build/outputs/apk/debug/*.apk


